name = "FrechetDistance"
uuid = "f187d5dc-b7e2-42ac-a77f-5bdb79d0423a"
authors = ["Benoît Richard <benoit.richard@desy.de>"]
version = "0.1.0"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
